# Generated by Django 3.0.2 on 2020-02-11 15:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vice_captain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vice_captain',
            name='vice_captain_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
